sudo: required

language: python
python:
      - "3.2"
      - "3.3"
      - "3.4"
      - "3.5"
      - "3.5-dev" # 3.5 development branch
      - "3.6"
      - "3.6-dev" # 3.6 development branch
      - "3.7-dev" # 3.7 development branch

services:
      - docker
before_install:
      - docker --version  # document the version travis is using
      - docker build -t parser .
      - docker run -d --rm -ti parser
script:
      - python start.py --file test-rules
